umaData = [
    ################# UMA ####################
    ### Oguri Cap ###
    {"name": "Pinned Hopes", "options": {"opt1": "Stamina +10, Power +10", "opt2": "Wisdom +20"}},
    {"name": "Oguri the Forest Guide?", "options": {"opt1": "Speed +20", "opt2": "Power +20"}},
    {"name": "Better Than a Plushie", "options": {"opt1": "Guts +20, (random) Get Hot Topic status", "opt2": "Stamina +20, (random) Get Hot Topic status"}},
    {"name": "Lost Umamusume", "options": {"opt1": "Guts +10", "opt2": "Speed +10"}},
    {"name": "Field Workout", "options": {"opt1": "Guts +10", "opt2": "Power +10"}},
    {"name": "Running on Full", "options": {"opt1": "Energy +10, Skill points +15", "opt2": "Nakayama Racecourse ○ hint +1"}},
    {"name": "Oguri's Gluttony Championship", "options": {"opt1": "Random: Energy + 30, Power +10, Skill points + 10, OR, Energy + 30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)", "opt2": "Energy + 10, Power +5, Skill points +5"}},
    {"name": "Bottomless Pit", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "Oguri Makes a Resolution", "options": {"opt1": "Spped +5, Wisdom +5", "opt2": "Stamina +5, Guts + 5"}},
    {"name": "Oguri Perseveres", "options": {"opt1": "Guts +10", "opt2": "Power +10"}},
    {"name": "Oguri Matures", "options": {"opt1": "Wisdom +10", "opt2": "Stamina +10", "opt3": "Power +10"}},
    {"name": "Something Smells Good!", "options": {"opt1": "Speed +10", "opt2": "Guts +10"}},
    {"name": "High-Level Rival", "options": {"opt1": "Speed +5, Stamina +5", "opt2": "Power +5, Wisdom +5"}},
    ### Symboli Rudolf ###
    {"name": "Midway Reflection", "options": {"opt1": "Speed +20", "opt2": "Power +20"}},
    {"name": "The Smiling Emperor's New Clothes", "options": {"opt1": "Wisdom +20", "opt2": "Guts +20"}},
    {"name": "The Distant View from the End of the Road", "options": {"opt1": "Stamina +20, (random) Get Hot Topic status", "opt2": "Guts +20, (random) Get Hot Topic status"}},
    {"name": "Those Who March Forth", "options": {"opt1": "Speed +5, Power +5", "opt2": "Stamina +5, Guts +5"}},
    {"name": "The Emperor's Social Studies", "options": {"opt1": "Energy -10, Stamina +10, Power +10", "opt2": "Wisdom +5, Skill points +15"}},
    {"name": "The Emperor's Spare Time", "options": {"opt1": "Wisdom +10, Skill points +15", "opt2": "Rainy Days ○ hint +1"}},
    {"name": "At Any Time", "options": {"opt1": "Energy -10, Guts +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "Sudden Kindness", "options": {"opt1": "Energy -10, Stamina +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "As Good As My Word", "options": {"opt1": "Energy -10, Power +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "The Emperor's Satiation", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random:, Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "Birds of a Feather", "options": {"opt1": "Speed +10", "opt2": "Stamina +10"}},
    {"name": "Well-Earned Respect", "options": {"opt1": "Wisdom +10", "opt2": "Power +10"}},
    {"name": "A Clear and Beautiful Night", "options": {"opt1": "Speed +10", "opt2": "Wisdom +10", "opt3": "Stamina +10"}},
    {"name": "The Emperor's Daily Routine", "options": {"opt1": "Power +10", "opt2": "Guts +10"}},
    {"name": "The Emperor's Path", "options": {"opt1": "Wisdom +10", "opt2": "Power +10"}},
    ### Nice Nature ###
    {"name": "Nature and Her Tired Trainer", "options": {"opt1": "Power +20", "opt2": "Stamina +20"}},
    {"name": "Bittersweet Sparkle", "options": {"opt1": "Power +20", "opt2": "Speed +20"}},
    {"name": "Festive Colors", "options": {"opt1": "Guts +20, (random) Get Charming ○ status", "opt2": "Stamina +20, (random) Get Charming ○ status"}},
    {"name": "Rainy-Day Fun", "options": {"opt1": "Wisdom +10", "opt2": "Energy -10, Stamina +10, Guts +10"}},
    {"name": "Not My Style", "options": {"opt1": "Energy +5, Mood +1", "opt2": "Speed +5, Power +5"}},
    {"name": "Whirlwind Advice", "options": {"opt1": "Studious hint +1", "opt2": "Speed +5, Stamina +5, Power +5"}},
    {"name": "A Little Can't Hurt", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "A Phone Call from Mom", "options": {"opt1": "Stamina +10", "opt2": "Speed +10"}},
    {"name": "Once in a While", "options": {"opt1": "Stamina +5, Guts +5", "opt2": "Stamina +5, Power +5"}},
    {"name": "Bittersweet Twilight", "options": {"opt1": "Speed +10", "opt2": "Guts +10", "opt3": "Wisdom +10"}},
    {"name": "Snapshot of Emotions", "options": {"opt1": "Speed +10", "opt2": "Power +10"}},
    {"name": "Let's Watch the Fish", "options": {"opt1": "Guts +10", "opt2": "Speed +10"}},
    # Placeholders
    {"name": "aaaaaa", "options": {"opt1": "aaaaaa", "opt2": "aaaaaa"}},
]