umaData = [
    ################# UMA ####################
    ### Oguri Cap ###
    {"name": "Pinned Hopes", "options": {"opt1": "Stamina +10, Power +10", "opt2": "Wisdom +20"}},
    {"name": "Oguri the Forest Guide?", "options": {"opt1": "Speed +20", "opt2": "Power +20"}},
    {"name": "Better Than a Plushie", "options": {"opt1": "Guts +20, (random) Get Hot Topic status", "opt2": "Stamina +20, (random) Get Hot Topic status"}},
    {"name": "Lost Umamusume", "options": {"opt1": "Guts +10", "opt2": "Speed +10"}},
    {"name": "Field Workout", "options": {"opt1": "Guts +10", "opt2": "Power +10"}},
    {"name": "Running on Full", "options": {"opt1": "Energy +10, Skill points +15", "opt2": "Nakayama Racecourse ○ hint +1"}},
    {"name": "Oguri's Gluttony Championship", "options": {"opt1": "Random: Energy + 30, Power +10, Skill points + 10, OR, Energy + 30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)", "opt2": "Energy + 10, Power +5, Skill points +5"}},
    {"name": "Bottomless Pit", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "Oguri Makes a Resolution", "options": {"opt1": "Spped +5, Wisdom +5", "opt2": "Stamina +5, Guts + 5"}},
    {"name": "Oguri Perseveres", "options": {"opt1": "Guts +10", "opt2": "Power +10"}},
    {"name": "Oguri Matures", "options": {"opt1": "Wisdom +10", "opt2": "Stamina +10", "opt3": "Power +10"}},
    {"name": "Something Smells Good!", "options": {"opt1": "Speed +10", "opt2": "Guts +10"}},
    {"name": "High-Level Rival", "options": {"opt1": "Speed +5, Stamina +5", "opt2": "Power +5, Wisdom +5"}},
    ### Symboli Rudolf ###
    {"name": "Midway Reflection", "options": {"opt1": "Speed +20", "opt2": "Power +20"}},
    {"name": "The Smiling Emperor's New Clothes", "options": {"opt1": "Wisdom +20", "opt2": "Guts +20"}},
    {"name": "The Distant View from the End of the Road", "options": {"opt1": "Stamina +20, (random) Get Hot Topic status", "opt2": "Guts +20, (random) Get Hot Topic status"}},
    {"name": "Those Who March Forth", "options": {"opt1": "Speed +5, Power +5", "opt2": "Stamina +5, Guts +5"}},
    {"name": "The Emperor's Social Studies", "options": {"opt1": "Energy -10, Stamina +10, Power +10", "opt2": "Wisdom +5, Skill points +15"}},
    {"name": "The Emperor's Spare Time", "options": {"opt1": "Wisdom +10, Skill points +15", "opt2": "Rainy Days ○ hint +1"}},
    {"name": "At Any Time", "options": {"opt1": "Energy -10, Guts +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "Sudden Kindness", "options": {"opt1": "Energy -10, Stamina +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "As Good As My Word", "options": {"opt1": "Energy -10, Power +20, Yayoi Akikawa bond +10", "opt2": "Energy +10"}},
    {"name": "The Emperor's Satiation", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random:, Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "Birds of a Feather", "options": {"opt1": "Speed +10", "opt2": "Stamina +10"}},
    {"name": "Well-Earned Respect", "options": {"opt1": "Wisdom +10", "opt2": "Power +10"}},
    {"name": "A Clear and Beautiful Night", "options": {"opt1": "Speed +10", "opt2": "Wisdom +10", "opt3": "Stamina +10"}},
    {"name": "The Emperor's Daily Routine", "options": {"opt1": "Power +10", "opt2": "Guts +10"}},
    {"name": "The Emperor's Path", "options": {"opt1": "Wisdom +10", "opt2": "Power +10"}},
    ### Nice Nature ###
    {"name": "Nature and Her Tired Trainer", "options": {"opt1": "Power +20", "opt2": "Stamina +20"}},
    {"name": "Bittersweet Sparkle", "options": {"opt1": "Power +20", "opt2": "Speed +20"}},
    {"name": "Festive Colors", "options": {"opt1": "Guts +20, (random) Get Charming ○ status", "opt2": "Stamina +20, (random) Get Charming ○ status"}},
    {"name": "Rainy-Day Fun", "options": {"opt1": "Wisdom +10", "opt2": "Energy -10, Stamina +10, Guts +10"}},
    {"name": "Not My Style", "options": {"opt1": "Energy +5, Mood +1", "opt2": "Speed +5, Power +5"}},
    {"name": "Whirlwind Advice", "options": {"opt1": "Studious hint +1", "opt2": "Speed +5, Stamina +5, Power +5"}},
    {"name": "A Little Can't Hurt", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Slow Metabolism (bad status)"}},
    {"name": "A Phone Call from Mom", "options": {"opt1": "Stamina +10", "opt2": "Speed +10"}},
    {"name": "Once in a While", "options": {"opt1": "Stamina +5, Guts +5", "opt2": "Stamina +5, Power +5"}},
    {"name": "Bittersweet Twilight", "options": {"opt1": "Speed +10", "opt2": "Guts +10", "opt3": "Wisdom +10"}},
    {"name": "Snapshot of Emotions", "options": {"opt1": "Speed +10", "opt2": "Power +10"}},
    {"name": "Let's Watch the Fish", "options": {"opt1": "Guts +10", "opt2": "Speed +10"}},
    ### Gold Ship ###
    {"name": "The Red of the Protagonist!", "options": {"opt1": "Wisdom +20", "opt2": "Guts +20"}},
    {"name": "A Date, Golshi Style", "options": {"opt1": "Stamina +20", "opt2": "Power +20"}},
    {"name": "A Sudden Episode from Golshi's Past!", "options": {"opt1": "Stamina +10, Wisdom +10, (random) Get Fast Learner status", "opt2": "Speed +20, (random) Get Fast Learner status"}},
    {"name": "Pair Discount Repeat Offender", "options": {"opt1": "Guts +10", "opt2": "Stamina +10"}},
    {"name": "Which Did You Lose?", "options": {"opt1": "Energy -10, Power +20", "opt2": "Speed +10"}},
    {"name": "My Part-Time Job Is... Crazy?", "options": {"opt1": "Stamina +10, Skill points +15", "opt2": "Hanshin Racecourse ○ hint +1"}},
    {"name": "The Day After, Voices Hoarse", "options": {"opt1": "Stamina +10", "opt2": "Guts +10"}},
    {"name": "This One's For Keeps!", "options": {"opt1": "Energy +10", "opt2": "Random: Skill points +60, Non-Standard Distance ○ hint +1, OR, Skill points +15, Get Slacker status"}},
    {"name": "Summer Camp (Year 3) Ends", "options": {"opt1": "3 random stats +5", "opt2": "3 random stats +5"}},
    {"name": "Killer Appetite!", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Legend of the Left Pinky", "options": {"opt1": "Stamina +10", "opt2": "Speed +10"}},
    {"name": "Hello From About 1.5 Billion Years Ago", "options": {"opt1": "Guts +10", "opt2": "Wisdom +10"}},
    {"name": "And Then She...", "options": {"opt1": "Speed +10", "opt2": "Guts +10", "opt3": "Power +10"}},
    {"name": "A Lovely Place", "options": {"opt1": "Stamina +10", "opt2": "Wisdom +10"}},
    {"name": "Nighttime Park Visit", "options": {"opt1": "Guts +10", "opt2": "Speed +10"}},
    ### Grass Wonder ###
    {"name": "Hidden Meaning", "options": {"opt1": "Stamina +10, Guts +10", "opt2": "Power +20"}},
    {"name": "Principles", "options": {"opt1": "Speed +20", "opt2": "Stamina +20"}},
    {"name": "Hate to Lose", "options": {"opt1": "Wisdom +20, (random) Get Fast Learner status", "opt2": "Stamina +10, Guts +10, (random) Get Fast Learner status"}},
    {"name": "Errands Have Perks", "options": {"opt1": "Speed +5, Stamina +5", "opt2": "Energy +5, Wisdom +5"}},
    {"name": "Beauteaful", "options": {"opt1": "Wisdom +5, Skill points +15", "opt2": "Speed +10"}},
    {"name": "Tracen Karuta Queen", "options": {"opt1": "Speed +10, Wisdom +5", "opt2": "Competitive Spirit ○ hint +1"}},
    {"name": "In Search of Refreshment", "options": {"opt1": "Mood -1, Guts +25", "opt2": "Mood -1, Wisdom +25"}},
    {"name": "Together for Tea", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: Energy +30, Skill points +10, OR, Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Yamato Nadeshiko", "options": {"opt1": "Power +5, Wisdom +5", "opt2": "Speed +10"}},
    {"name": "Childhoods Apart", "options": {"opt1": "Guts +10", "opt2": "Stamina +10"}},
    {"name": "Nadeshiko Gal", "options": {"opt1": "Power +10", "opt2": "Wisdom +10", "opt3": "Speed +10"}},
    {"name": "Childhood Dream", "options": {"opt1": "Speed +5, Guts +5", "opt2": "Stamina +5, Wisdom +5"}},
    {"name": "Flower Vase", "options": {"opt1": "Guts +5, Wisdom +5", "opt2": "Speed +5, Stamina +5"}},
    ### Matikanefukukitaru ###
    {"name": "Room of the Chosen Ones", "options": {"opt1": "Guts +20", "opt2": "Speed +20"}},
    {"name": "Better Fortune! Lucky Telephone", "options": {"opt1": "Stamina +10, Wisdom +10", "opt2": "Power +20"}},
    {"name": "Under the Meteor Shower", "options": {"opt1": "Speed +10, Power +10, (random) Get Charming ○ status", "opt2": "Stamina +10, Guts +10, (random) Get Charming ○ status"}},
    {"name": "Cursed Camera", "options": {"opt1": "Wisdom +10", "opt2": "Skill points +30"}},
    {"name": "Manhattan's Dream", "options": {"opt1": "Hesitant Front Runners hint +1", "opt2": "Stamina +10"}},
    {"name": "Pretty Gunslingers", "options": {"opt1": "Skill points +15, Mood +1", "opt2": "Power +10"}},
    {"name": "Which One is the Lucky Card?!", "options": {"opt1": "Random: Speed +5, Stamina +5, OR, Mood +1, Skill points +15, OR, Mood -1"}},
    {"name": "Seven Gods of Fortune Fine Food Tour", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Fukukitaru's Protection against Misfortune", "options": {"opt1": "Guts +10", "opt2": "Power +10"}},
    {"name": "Punch in a Pinch", "options": {"opt1": "Speed +10", "opt2": "Stamina +5, Wisdom +5"}},
    {"name": "Fukukitaru's Unique Good-Luck Spell", "options": {"opt1": "Speed +5, Guts +5", "opt2": "Stamina +5, Power +5", "opt3": "Wisdom +10"}},
    {"name": "Taking the Plunge", "options": {"opt1": "Stamina +10", "opt2": "Speed +5, Wisdom +5"}},
    {"name": "Shrine Visit", "options": {"opt1": "Power +5, Guts +5", "opt2": "Speed +5, Stamina +5"}},
    ## Agnes Tachyon ##
    {"name": "Expression of Conviction", "options": {"opt1": "Stamina +20", "opt2": "Speed +20"}},
    {"name": "Obtain Data!", "options": {"opt1": "Wisdom +20", "opt2": "Power +20"}},
    {"name": "Tachyon the Spoiled Child", "options": {"opt1": "Stamina +10, Guts +10, (random) Get Fast Learner status", "opt2": "Wisdom +20, (random) Get Fast Learner status"}},
    {"name": "At Tachyon's Pace", "options": {"opt1": "Guts +10", "opt2": "Speed +5, Power +5"}},
    {"name": "The Strongest Collaborator?!", "options": {"opt1": "Energy -20, Stamina +15, Guts +10", "opt2": "Energy +5, Wisdom +5"}},
    {"name": "The Pressure of Justice?", "options": {"opt1": "Wisdom +10, Skill points +15", "opt2": "Corner Adept ○ hint +1"}},
    {"name": "Hamburger Helper!", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Medicine That Makes You Faster?", "options": {"opt1": "Power +5, Guts +5", "opt2": "Speed +5, Wisdom +5"}},
    {"name": "The Significance of Research", "options": {"opt1": "Wisdom +10", "opt2": "Speed +10"}},
    {"name": "No Shortcuts", "options": {"opt1": "Guts +10", "opt2": "Wisdom +10", "opt3": "Power +10"}},
    {"name": "A Gift From the Dark Sky", "options": {"opt1": "Speed +5, Power +5", "opt2": "Guts +10"}},
    {"name": "Body Modification!", "options": {"opt1": "Power +5, Wisdom +5", "opt2": "Stamina +10"}},
    ## Vodka ##
    {"name": "Vintage Style", "options": {"opt1": "Power +20", "opt2": "Stamina +20"}},
    {"name": "Makings of a Friend", "options": {"opt1": "Speed +20, (random) Get Practice Perfect ○ status", "opt2": "Guts +20"}},
    {"name": "Hot and Cool", "options": {"opt1": "Speed +20, (random) Get Practice Perfect ○ status", "opt2": "Speed +10, Power +10, (random) Get Practice Perfect ○ status"}},
    {"name": "Like a Kid", "options": {"opt1": "Speed +10", "opt2": "Power +10"}},
    {"name": "Challenging Fate", "options": {"opt1": "Stamina +10", "opt2": "Speed +10"}},
    {"name": "Showdown by the River!", "options": {"opt1": "Wisdom +10, Skill points +15", "opt2": "Shifting Gears hint +1"}},
    {"name": "Awkward Honesty", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "The Standards of Coolness", "options": {"opt1": "Wisdom +10", "opt2": "Guts +10"}},
    {"name": "Ring Out, Passionate Sound!", "options": {"opt1": "Speed +10", "opt2": "Stamina +10"}},
    {"name": "The Way of Cool", "options": {"opt1": "Power +10", "opt2": "Speed +10", "opt3": "Stamina +5, Guts +5"}},
    {"name": "Let's Take a Little Detour", "options": {"opt1": "Speed +10", "opt2": "Energy +5, Mood +1"}},
    {"name": "Sugar and Spice", "options": {"opt1": "Energy +5/+10", "opt2": "Power +10"}},
    ## Taiki Shutter
    {"name": "Quick Draw Showdown", "options": {"opt1": "Energy +10, Speed +10", "opt2": "Energy +10, Wisdom +10"}},
    {"name": "Must-Win Match", "options": {"opt1": "Wisdom +20", "opt2": "Stamina +20"}},
    {"name": "To the Top!", "options": {"opt1": "Power +10, Guts +10, (random) Get Fast Learner status", "opt2": "Speed +10, Wisdom +10, (random) Get Fast Learner status"}},
    {"name": "Hide-and-Seek", "options": {"opt1": "Speed +10", "opt2": "Stamina +10"}},
    {"name": "Embracing Guidance", "options": {"opt1": "Power +10", "opt2": "Energy +10"}},
    {"name": "Harvest Festival", "options": {"opt1": "Power +10, Skill points +15", "opt2": "Prepared to Pass hint +1"}},
    {"name": "Serial Riddler", "options": {"opt1": "Random: Mood +1, Stamina +5, Power +10, OR, Mood -1", "opt2": "Wisdom +10"}},
    {"name": "Taste of Home", "options": {"opt1": "Random: Mood +1, Speed +10, Power +5, OR, Mood -1", "opt2": "Wisdom +10"}},
    {"name": "Meaty Heaven", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Rainy Power", "options": {"opt1": "Power +10", "opt2": "Skill points +30"}},
    {"name": "Rainy Choice", "options": {"opt1": "Speed +5, Guts +5", "opt2": "Stamina +5, Wisdom +5"}},
    {"name": "Rainy Rescue", "options": {"opt1": "Skill points +30", "opt2": "Power +5, Wisdom +5", "opt3": "Speed +5, Guts +5"}},
    {"name": "Let's Patrol!", "options": {"opt1": "Power +10", "opt2": "Energy +10"}},
    {"name": "Going Home Together", "options": {"opt1": "Mood +1, Speed +5", "opt2": "Mood +1, Stamina +5"}},
    ## Mejiro Ryan ##
    {"name": "My Signature Racewear", "options": {"opt1": "Guts +20", "opt2": "Speed +20"}},
    {"name": "Heart-Pounding Aquarium", "options": {"opt1": "Power +10, Wisdom +10", "opt2": "Stamina +10, Wisdom +10"}},
    {"name": "Refreshingly Real", "options": {"opt1": "Stamina +20, (random) Get Hot Topic status", "opt2": "Power +20, (random) Get Hot Topic status"}},
    {"name": "Muscle Jealousy", "options": {"opt1": "Guts +10", "opt2": "Wisdom +10"}},
    {"name": "The Pony Girl and the Wolf Prince", "options": {"opt1": "Energy +5, Stamina +5", "opt2": "Energy +5, Speed +5"}},
    {"name": "Real Gains", "options": {"opt1": "Power +10, Skill points +15", "opt2": "Wet Conditions ○ hint +1"}},
    {"name": "Rest Day", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "Nerve-Racking Rest Time", "options": {"opt1": "Stamina +10", "opt2": "Power +10"}},
    {"name": "Flush with Feelings", "options": {"opt1": "Wisdom +10", "opt2": "Speed +10"}},
    {"name": "With Relaxation and Trust Comes...", "options": {"opt1": "Speed +10", "opt2": "Stamina +10", "opt3": "Power +10"}},
    {"name": "Ryan to the Rescue!", "options": {"opt1": "Power +10", "opt2": "Guts +10"}},
    {"name": "The Little Fans of the Umadol", "options": {"opt1": "Power +10", "opt2": "Wisdom +10"}},
    ## Daiwa Scarlet ##
    {"name": "The Best Pose", "options": {"opt1": "Stamina +10, Power +10", "opt2": "Wisdom +20"}},
    {"name": "The Weight of Racewear", "options": {"opt1": "Speed +20", "opt2": "Guts +20"}},
    {"name": "Looking Good", "options": {"opt1": "Stamina +10, Wisdom +10, (random) Get Hot Topic status", "opt2": "Speed +10, Guts +10, (random) Get Hot Topic status"}},
    {"name": "Her", "options": {"opt1": "Power +5, Objective race changed to Japanese Oaks", "opt2": "Power +5, Objective race changed to Tokyo Yushun (Japanese Derby)"}},
    {"name": "Recommended Restaurant", "options": {"opt1": "Speed +5, Power +5", "opt2": "Guts +5, Mood +1"}},
    {"name": "Advice from an Older Student", "options": {"opt1": "Speed +10", "opt2": "Power +10"}},
    {"name": "Enjoying Number One", "options": {"opt1": "Stamina +10, Skill points +15", "opt2": "Unyielding Spirit hint +1"}},
    {"name": "Can't Lose Sight of Number One!", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "As a Model Student...", "options": {"opt1": "Wisdom +10", "opt2": "Skill points +30"}},
    {"name": "Just a Little More", "options": {"opt1": "Skill points +30", "opt2": "Power +10"}},
    {"name": "Under the Evening Star", "options": {"opt1": "Skill points +30", "opt2": "Speed +5, Stamina +5", "opt3": "Power +10"}},
    {"name": "Rained On", "options": {"opt1": "Guts +10", "opt2": "Wisdom +10"}},
    {"name": "How to Spend a Day Off", "options": {"opt1": "Energy +10", "opt2": "Mood +1, Wisdom +5"}},
    ## Haru Urara ##
    {"name": "The Racewear I Love!", "options": {"opt1": "Speed +20", "opt2": "Power +20"}},
    {"name": "Pair Interview!", "options": {"opt1": "Power +20", "opt2": "Stamina +20"}},
    {"name": "Tug of War Tournament!", "options": {"opt1": "Guts +20, (random) Get Hot Topic status", "opt2": "Speed +20, (random) Get Hot Topic status"}},
    {"name": "Arm-Wrestling Contest", "options": {"opt1": "Wisdom +10", "opt2": "Power +10"}},
    {"name": "Looking for Something Important", "options": {"opt1": "Energy -10, Guts +20", "opt2": "Stamina +10"}},
    {"name": "Sand Training!", "options": {"opt1": "Guts +10, Skill points +15", "opt2": "Energy +15"}},
    {"name": "The Final Boss... Spe!", "options": {"opt1": "Energy +10, Skill points +5", "opt2": "Random: (~90%) Energy +30, Skill points +10, OR, (~10%) Energy +30, Skill points +10, Speed -5, Power +5, Get Slow Metabolism status"}},
    {"name": "A Little Detour!", "options": {"opt1": "Skill points +30", "opt2": "Stamina +10"}},
    {"name": "Parks Are Fun!", "options": {"opt1": "Speed +10", "opt2": "Power +10"}},
    {"name": "Secret Day Off Plan!", "options": {"opt1": "Speed +10", "opt2": "Power +10", "opt3": "Wisdom +10"}},
    {"name": "So Cool!", "options": {"opt1": "Skill points +30", "opt2": "Wisdom +10"}},
    {"name": "Forgot to Eat!", "options": {"opt1": "Guts +10", "opt2": "Stamina +10"}},
    # Placeholders
    {"name": "aaaaaa", "options": {"opt1": "aaaaaa", "opt2": "aaaaaa"}},
]